# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-cloud.yml if you use the "cloud" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# Spring boot properties
spring:
  main:
    show-banner: false
  messages:
    basename: classpath:/i18n/messages
  mvc:
    favicon:
      enabled: false
 

server:
  port: ${port:8091}
#  contextPath: /

facebook:
    callbackUrl: ${CALLBACK_URL}
    verifyToken: ${VERIFYTOKEN}
    pageAccessToken: ${ACCESSTOKEN}

#you should set the above properties in your environment variable